set :application, "music.ghostandthemachines.com"
set :user,        "ghostandthemachine"
set :repository, "ssh://50.56.236.164/music/.git/"
set :domain, "50.56.236.164"
set :deploy_to, "/home/ghostandthemachine/sites/#{application}"
